### ISSUE TITLE
2.6.6 to 3.0.0 issue: Too many re-renders

### ISSUE THREAD

**Issue by DrYSG** [ctrlplusb/easy-peasy#272]
I have a project (uses uses a DevExtreme Data grid bound to EasyPeasyStore) that loads/works fine with    "easy-peasy": "^2.6.6", but when I switch to 3.0.0  I am getting the following issue on load:

I wanted to create a CodeSandBox for you, but the latest version of CSB seems to be broken. When they fix this I will update this ticket with a link to that. But I wanted to give you a heads up about this.

```
Uncaught Error: An error occurred trying to map state in a useStoreState hook: Too many re-renders. React limits the number of renders to prevent an infinite loop..
This error may be related to the following error:
Invariant Violation: Too many re-renders. React limits the number of renders to prevent an infinite loop.
    at invariant (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:3430:19)
    at dispatchAction (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:17376:48)
    at checkMapState (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161366:9)
    at Object.dispatch (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:160553:7)
    at e (<anonymous>:1:40553)
    at https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161948:22
    at https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161012:16
    at Object.dispatch (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161984:16)
    at Object.dispatch (<anonymous>:1:28545)
    at actionCreator (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161630:37)

Original stack trace:
    at useStoreState (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161340:15)
    at OpList (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:171051:47)
    at renderWithHooks (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:16839:22)
    at updateFunctionComponent (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:18572:24)
    at beginWork (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:19625:20)
    at performUnitOfWork (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:23652:16)
    at workLoop (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:23693:28)
    at HTMLUnknownElement.callCallback (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:3520:18)
    at Object.invokeGuardedCallbackDev (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:3569:20)
    at invokeGuardedCallback (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:3623:35)
useStoreState @ hooks.js:42
OpList @ Oplist.jsx:23
renderWithHooks @ react-dom.development.js:12960
updateFunctionComponent @ react-dom.development.js:14627
beginWork @ react-dom.development.js:15637
performUnitOfWork @ react-dom.development.js:19312
workLoop @ react-dom.development.js:19352
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:18578
renderRoot @ react-dom.development.js:19468
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
render @ react-dom.development.js:21155
parcelRequire.components/OperationTables/Main.jsx.react @ Main.jsx:7
newRequire @ Main.8c01d644.js:47
(anonymous) @ Main.8c01d644.js:81
(anonymous) @ Main.8c01d644.js:120
react-dom.development.js:134 [Violation] 'react-invokeguardedcallback' handler took 3565ms
react-dom.development.js:17117 The above error occurred in the <OpList> component:
    in OpList (created by WithStyles(OpList))
    in WithStyles(OpList) (created by App)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by App)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by App)
    in App (created by WithStyles(App))
    in WithStyles(App) (created by App)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by App)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by App)
    in App (created by WithStyles(App))
    in WithStyles(App)
    in StoreProvider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

hooks.js:42 Uncaught Error: An error occurred trying to map state in a useStoreState hook: Too many re-renders. React limits the number of renders to prevent an infinite loop..
This error may be related to the following error:
Invariant Violation: Too many re-renders. React limits the number of renders to prevent an infinite loop.
    at invariant (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:3430:19)
    at dispatchAction (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:17376:48)
    at checkMapState (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161366:9)
    at Object.dispatch (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:160553:7)
    at e (<anonymous>:1:40553)
    at https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161948:22
    at https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161012:16
    at Object.dispatch (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161984:16)
    at Object.dispatch (<anonymous>:1:28545)
    at actionCreator (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161630:37)

Original stack trace:
    at useStoreState (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:161340:15)
    at OpList (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:171051:47)
    at renderWithHooks (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:16839:22)
    at updateFunctionComponent (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:18572:24)
    at beginWork (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:19625:20)
    at performUnitOfWork (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:23652:16)
    at workLoop (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:23693:28)
    at renderRoot (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:23773:11)
    at performWorkOnRoot (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:24730:11)
    at performWork (https://ysg4206.draper.com/Master/dist/Main.8c01d644.js:24640:11)
useStoreState @ hooks.js:42
OpList @ Oplist.jsx:23
renderWithHooks @ react-dom.development.js:12960
updateFunctionComponent @ react-dom.development.js:14627
beginWork @ react-dom.development.js:15637
performUnitOfWork @ react-dom.development.js:19312
workLoop @ react-dom.development.js:19352
renderRoot @ react-dom.development.js:19435
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
render @ react-dom.development.js:21155
parcelRequire.components/OperationTables/Main.jsx.react @ Main.jsx:7
newRequire @ Main.8c01d644.js:47
(anonymous) @ Main.8c01d644.js:81
(anonymous) @ Main.8c01d644.js:120
hmr-runtime.js:29 WebSocket connection to 'wss://ysg4206.draper.com:61768/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
```

**Comment by ctrlplusb** [comment]
Looking at the stack trace it appears that you are firing an action for every render of your component tree. An example would certainly help.

**Comment by DrYSG** [comment]
CodeSandBox had a upgrade, and when I chose it yesterday, it broke all my sandboxes. They fixed it today.

I put it my full working component into:

https://codesandbox.io/s/easypeasy-266-wgxyy

When you click on any item in the lower table, it will be added to the upper table (both are DevExtreme DataGrids). There might well be an shorter version that will also give the same bug. I can give a quick overview of how the grid works, so let's not let that stop us.

The fork of the exact same source and dependencies is located at:

https://codesandbox.io/s/easypeasy-300-4frtu

with one small change, Easy-Peasy-2.6.6 -> 3.0.0

There you will see the infinite re-render loop. Yes, I know that is the problem, but it is hard more me to grok why that would occur just by switching to version 3.0.0.

**Comment by ctrlplusb** [comment]
Hey @DrYSG 

Thanks for the codesandbox. I can see exactly what is going on.

This behaviour has been introduced by v3.0.0 because of a bug fix on the `useStoreState` hook. I won't go into the details, because I don't think it has too much bearing on the actual issue here.

Firstly, I _strongly_ recommend to never do any operations or data mapping like you have done within the `useStoreState` hook. If you need to derive data, either introduce a computed property, or return the raw data from the state and then wrap the deriving code within a `useMemo` hook.

I have gone ahead and refactored your application, utilising some of the native React hooks to help us.

**Before:**

```javascript
const source = useStoreState(state => {
    const store = new ArrayStore({
        key: "OpSequence",
        data: state.opList
    })

    // 🚨
    // Anti pattern as this creates a new instance, breaking the equality
	// check optimisations of the useStoreState hook. The returned data
    // of this useStoreState hook implementation will never be === to the
    // the previously mapped state. Therefore any time any update happens
    // to any part of your state, even state this component doesn't care
    // about, the component will re-render.
    const opListData = new DataSource({
        store: store
    })

    // 🚨
    // Anti pattern. Never dispatch within a map state. This function gets
    // executed and checked every time a state update occurs on your store,
    // so you would get this action dispatched for every update on any
    // part of your store state  
    setGridStore(opListData)
    return opListData
})
```

**After:**

We can fix the above with the following:

```javascript
// 1. Only return the actual state you care about in this context, without
//    doing any data deriving.
const opList = useStoreState(state => state.opList);

// 2. We can utilise useMemo hook, providing the opList state as a dependency.
//    It will only be re-executed if and when the opList data changes.
const source = useMemo(() => {
  const store = new ArrayStore({
    key: 'OpSequence',
    data: opList,
  });
  return new DataSource({
    store: store,
  });
}, [opList]);

// 3. We can utilise an effect, tracking the "source" DataSource. Every time
//    it changes we can dispatch the action. Again this would only happen
//    if the actual opList state changed - which would have resulted in the 
//    DataSource being recreated within the useMemo hook.
useEffect(() => {
  setGridStore(source);
}, [setGridStore, source]);
```

**Demo:** https://codesandbox.io/s/easypeasy-300-jhuwo

**Comment by DrYSG** [comment]
@ctrlplusb 

Wow, what a quick fix, and I really appreciate your time. I am doing my best to advertise easy-peasy. Probably worth writing a new medium article when the dust settles and see if we cannot get this greater visibility.

1. I did not understand the api documentation article about the mapping anti-pattern. I thought it was only about mapping. Maybe it could be more clear, and simple say: 

> Only return the actual state you care about in this context, without doing any data deriving. e,.g do only:

```
const opList = useStoreState(state => state.opList);

```
2.  I modified your solution a good deal. 

Mainly because I see you have not seen either Kendo's or DevExtreme's DataSource idea: 
https://js.devexpress.com/Documentation/Guide/Data_Layer/Data_Layer/

It is a wrapper for Plain JSON data arrays to provide CRUD & Filter, and Paging, and Grouping of data for HOC components such as DataGrids, Charts, PivotTables, etc. So you should only hydrate the DataSouce once, and then do all data manipulations on the DataSouce object, not the original OpList coming from the EasyPeasy Store.

See my final result at: https://codesandbox.io/s/easypeasy-300-4frtu


![image](https://user-images.githubusercontent.com/2865368/61959399-4f799e80-af91-11e9-9cbe-d5d4a2612084.png)
