### ISSUE TITLE
Error useStoreState hook. Cannot perform 'get' on a proxy that has been revoked.

### ISSUE THREAD

**Issue by simkea** [ctrlplusb/easy-peasy#541]
My setup:
React 16.9.46
Easy-Peasy: 4.0.0-alpha.0 | also 3.3.1 and 3.4. tested

if i remove the reducer on prop "urlhash" then the error does not occur!
This still worked in the old version 2.6.6. !!!

and now my Problem:

Uncaught Error: An error occurred trying to map state in a useStoreState hook: Cannot perform 'get' on a proxy that has been revoked.
This error may be related to the following error:
TypeError: Cannot perform 'get' on a proxy that has been revoked
    at Object.eval [as current] (webpack-internal:///./src/components/AppBar.js:39:100)
    at checkMapState (webpack-internal:///./node_modules/easy-peasy/dist/easy-peasy.esm.js:89:38)
    at Object.dispatch (webpack-internal:///./node_modules/redux/es/redux.js:230:7)
    at e (<anonymous>:1:40553)
    at eval (webpack-internal:///./node_modules/easy-peasy/dist/easy-peasy.esm.js:569:21)
    at eval (webpack-internal:///./node_modules/easy-peasy/dist/easy-peasy.esm.js:838:22)
    at eval (webpack-internal:///./node_modules/redux-thunk/es/index.js:12:16)
    at Object.eval [as dispatch] (webpack-internal:///./node_modules/easy-peasy/dist/easy-peasy.esm.js:921:16)
    at Object.dispatch (<anonymous>:1:28545)
    at actionCreator (webpack-internal:///./node_modules/easy-peasy/dist/easy-peasy.esm.js:799:16)

My Store:
```
const app = {
    // Aktion because action is already declared in upper scope
    urlhash: reducer((state, aktion) => {
        console.log(state, aktion);
        if (aktion.type === 'HASH') {
            // eslint-disable-next-line no-param-reassign
            state = aktion.payload;
        }
        return state;
    }),
}
```

My Component:
```
export default function AppBar() {
    const hash = useStoreState(state => state.app.urlhash);
    const isLoggedIn = useStoreState(state => state.app.isLoggedIn);
    return ();
}
```

**Comment by ctrlplusb** [comment]
Hi @simkea;

I believe this is because you are trying to reassign the incoming `state` argument.

Instead try returning the payload:

```javascript
const app = {
    // Aktion because action is already declared in upper scope
    urlhash: reducer((state, aktion) => {
        console.log(state, aktion);
        if (aktion.type === 'HASH') {
            return aktion.payload; // 👈
        }
        return state;
    }),
}
```

Hope that helps. 🙏
