### ISSUE TITLE
Next.js prerender error: `Cannot read property 'getState' of undefined`

### ISSUE THREAD

**Issue by baptisteArno** [ctrlplusb/easy-peasy#701]
I migrated from CRA to Next.js and I'm using the latest version of easy-peasy but when I try to build it throws this error for each page using easy peasy hooks:

```
Error occurred prerendering page "...". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read property 'getState' of undefined
    at useStoreState (/Users/baptistearnaud/Dev/typebot-io/builder/node_modules/easy-peasy/dist/index.cjs.js:43:43)
    at App (/Users/baptistearnaud/Dev/typebot-io/builder/.next/server/pages/_app.js:185:50)
    at d (/Users/baptistearnaud/Dev/typebot-io/builder/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/Users/baptistearnaud/Dev/typebot-io/builder/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/Users/baptistearnaud/Dev/typebot-io/builder/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/Users/baptistearnaud/Dev/typebot-io/builder/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (/Users/baptistearnaud/Dev/typebot-io/builder/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/Users/baptistearnaud/Dev/typebot-io/builder/node_modules/next/dist/server/render.js:596:45)
    at Function.getInitialProps (/Users/baptistearnaud/Dev/typebot-io/builder/.next/server/chunks/6859.js:603:19)
    at Function.getInitialProps (/Users/baptistearnaud/Dev/typebot-io/builder/.next/server/pages/_document.js:30:83)
```

I tried nuking node_modules and install everything but it didn't work. Any idea?

**Comment by baptisteArno** [comment]
I used a hook on the `App` component that isn't wrapped with the `StoreProvider`
